version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build  # EC2 내부 배포 할 위치
    overwrite: yes

permissions:
  - object: /home/ubuntu/build
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755 
    
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh    # ApplicationStart 단계에서 해당 파일을 실행해라
      timeout: 60
      runas: root
