version: 0.2

batch:
  fast-fail: false

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - scripts/start.sh
    - scripts/before.sh
    - scripts/deploy.sh
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
